name: api-invoice

services:
  webapi:
    container_name: api-invoice
    image: ghcr.io/crispancho93/invoice.api:latest
    restart: always
    ports:
      - "10480:8000"
    volumes:
      - store-invoice:/srv/files
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=info
    command: >
      uvicorn app:app
      --host 0.0.0.0
      --port 8000
    networks:
      - odoo_network_2026

volumes:
  store-invoice:
    external: true

networks:
  odoo_network_2026:
    external: true
